//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TagCloudGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TagCloudGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Di 
        ///
        ///
        ///
        ///
        ///? R 1 T ! Fv H 
        ///
        ///
        ///
        ///
        ///
        ///
        ///1 1 1 u i Or 
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///a–  a–  &apos;.&apos;a– a– &apos; ,.........&apos; a–  a€?a– &apos; 
        ///
        ///
        ///
        ///THE 
        ///
        ///
        ///
        ///BRITISH CONSTITUTION 
        ///
        ///
        ///
        ///BY THE LATE 
        ///
        ///AMOS DEAN, LL.D., 
        ///
        ///Professor in the Albany Law School. 
        ///Author of &quot; History of Civilization,&quot; &quot; Commercial Law,&quot; Etc. 
        ///
        ///
        ///
        ///
        ///ROCHESTER, N. Y. 
        ///
        ///lawyers&apos; co-operative publishing company. 
        ///
        ///1893. 
        ///
        ///
        ///
        ///COPTRIGHT, 1883, 
        ///
        ///By AMOS H. DEAN. 
        ///
        ///
        ///
        ///E. R. Andrews, Printer ant&gt; Rookbindep 
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///7 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BritishConstitution {
            get {
                return ResourceManager.GetString("BritishConstitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to i
        ///me
        ///my
        ///myself
        ///we
        ///our
        ///ours
        ///ourselves
        ///you
        ///your
        ///yours
        ///yourself
        ///yourselves
        ///he
        ///him
        ///his
        ///himself
        ///she
        ///her
        ///hers
        ///herself
        ///it
        ///its
        ///itself
        ///they
        ///them
        ///their
        ///theirs
        ///themselves
        ///what
        ///which
        ///who
        ///whom
        ///this
        ///that
        ///these
        ///those
        ///am
        ///is
        ///are
        ///was
        ///were
        ///be
        ///been
        ///being
        ///have
        ///has
        ///had
        ///having
        ///do
        ///does
        ///did
        ///doing
        ///a
        ///an
        ///the
        ///and
        ///but
        ///if
        ///or
        ///because
        ///as
        ///until
        ///while
        ///of
        ///at
        ///by
        ///for
        ///with
        ///about
        ///against
        ///between
        ///into
        ///through
        ///during
        ///before
        ///after
        ///above
        ///below
        ///to
        ///from
        ///up
        ///down
        ///in
        ///out
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Stopwords {
            get {
                return ResourceManager.GetString("Stopwords", resourceCulture);
            }
        }
    }
}
